Layout.layouts["en"] = {"name": "English",
    "icon": "iVBORw0KGgoAAAANSUhEUgAAACAAAAAcCAYAAAAAwr0iAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAA2RpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDozRUYwNDlGNzVGREQxMUUyQkM2MDk5QzBCRTQyNjExQiIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDozRUYwNDlGNjVGREQxMUUyQkM2MDk5QzBCRTQyNjExQiIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ1M1IFdpbmRvd3MiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDo1OUVDNTc3RkQzNUZFMjExQjZCMkMzMkRFRjFGMDVEQSIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/PsYQet8AAAaxSURBVHjaxFcLUFRlFP7u7t1dWGARdRENfBSKg6/AxlIzswQfU2ZZlKbhA4kyo9LKml6m02jZIBXKI6exh4WTTQ970GBhNJUlI0abq5GEi6y4obC77Pvu37n/vbBo0yjTlGfmzP33/Pc/5/znfOecuwJjDJeSNLjEJE6ZMkWbnJxsMJvNWoPBAI3mv/UpHA7D7/fD4XBILS0tftHpdJp2FKw+EzvjWgiCgNOnXaipsaKjwy37d/5xHrT8/Glor3gbgkbgUhZmGLByMcrLa+mXRKw971wI/Qb2w3WThiLu18PwWI8h+vaxuGZ1QX+xqakp3vXWblkNjFdfhcTEOMyfnwmLpQU22xk1S8I5DsikS0qkpSpXcZSUFH+eA4o8ZYQZo816sCO/8N2EnAUQk8yQbYsej8cQWrEMQvMxtG/fAdPcbESlpyEjYxj0eh2qqy1wd3khMB2YIJErWsybNx6+hiMUIK1inCJguikbDQ0naT9E/sqRC8JoikPW9aOQ6mqBc28tdCNTYZqTBU2MEY4/3ZBt8xg/UlqHZ9dmIzXmMNpLymC8dir6LZiHMWOGwEwRqXzvAKzWFvX2SloCrXYIWmXNJIk/W1vPcsMypU24AjlThyCm+iM4fmtC/IL5iJsxle9ZLCdRVFQVqQJ7Uxt2vPk9PsYwmJbcjeCBA7Bv2Az/b8eRaI7DqgduRFbWBHi9fmLFAPP4wLxehX1eLpP3vP4QZs6diLx0EUJpCdydbiSuLeTGg1IYu3f/hIqK/bDbOyMOhEIC3E4fPni3Fi9+5UBo5f2I0YuwP7UenXu/pFQLhIsMrFqVha6ugIIGjxeSyuEuxQF5L3/5dMz6sx6OV1+DLiMTg59cA/3wZLS1ubBh/cfYs+cHuN0BsqmWoeKAHy6XhxQEcei7ehRSiAqW3oQrk1PQXloO3+EGDMi7BxMnDkdl5UrFATdViU6tkpCSgl0lt6H9hS1oa7bBfN+9iJ05DSHCxzdfWVFW9jXpd9JbemIPAgFPbwcYnE4/gSLIg+JyteP5jZ/hsXVzkV00Gd7GRkguFzTxJmiiDKoDHgi6bgwo1wl1OhE1+wb0p5uL5gFcVlVlwYubvlCrQsurRJKC8PmUapLrKI0ag1UUxT41oWOTZhEItT0gHPVjVZ+aUYhyQI1vNL/C0XHTIcZEQ/Ap+aWO1FPbfN2bZDnJBB2VpYx49bd17HWRM/9E6rvMoIMUCEVSQAVOaPZTBQUv+hYsEPi78os9SxFgarTF7hxKTsppHxz4N8QoejDF9gIhoVPb5YPQXRsXJC2BUa+ulRSFfX61DV+EA4S3sMAiDqT/UU9tV98nEP4cPZTjgCskx8d7m/sEwoCcwuhoxYHBSWsQCGpIeO4Nyl9fjGW5UxQjwRB8R6y8TKPHp9Nl6V21CiBFzoW7PNQZ/fCfaEZUSgp2fnoU+Xlvn6NXr9cSs0gnDIaCfGQyJrMHOl0YW7bchoV3TeIvuaprYRmZCfviPBgS+0dAx8LydXqmHldIg0bq7IT9mc2wDBuD2Y5DeKVkIaLjDXSki9uQbcm9oFcrVpbhsBcjRyZj//7HUVg4E1E0q9peKMLv2XMwZHIGmtcXQxzyXM83AGemPLkGTQH27TsC/eXDccVH72Dg2odw6rFHcUfVNtRU5mLM1WO5DRk3wWC4x+k0UcxlRuNytnBhGWs77WIy+ZtOsMab72IWXQLrfGkrK62oZcaEVWQpn+/XC4PYYUMy53ptEpfJewbDUlZcXM26qePDz1nDZaNZU+o4dvKDKrZ09W6ylU+FkCt7ncYjYDSKNB6XYNeufJp+seh4/xNYM6dB13gUpspKPHA8CQUrd8BztvOCAPPTNCws3ImcnO04dcqJ+FtmY/Shb8EmZODsHXeieHAzSrbnwmQ2RSJQU3OIUTtmAaeLHb9vDatDLDv94Br2xZ7v2aiM9eTpIuIVxPcQ51EPCrCDFIE6w2WcD1IEZJm8ByxRn4vYiBFr2d699XxP5tbiMnZQP5C13JrDvnzzEx4BPgtsNptVZ2uF7eEnoWm1IeG5p1F6IgZlJdWQ+KzvrvkAX9tsm/Dr0EwIerWR0jRM/6MOKSnret5RKMhLe/nyaXh83RzClA6+X6xoefgJeBqPY3rHCT4LJPsbu9D6UhGMqSPge3oD8nc2oO6bn1VFwjkfl3LrsNvtaHM7e01DCQkkc7vPqF9Eut5tB1u3vk/grMPGjbcSyAfBWF4E78vbgHcqJFn7IOJxxOb/+S+Bg7hBdkAe8HHq8/8kuXe7hEv91+wvAQYAsaE9RMg/tfAAAAAASUVORK5CYII=",
    "sets":['all'],
    
    "all":['`', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', 'backspace', 'EOL',
           'tab', 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '[', ']', '\\', 'EOL',
           '{capslock}', 'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', '\'', 'returnUS', 'EOL',
           '[shiftUS]', 'z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '/', '[rightshift]', 'EOL',
           'selector', '[alt]', 'space', '[alt]', 'EOL'],
    "all_alt":['`', '¡','™','£','¢','∞','§','¶','•','ª','º','–','≠', 'backspace', 'EOL',
               'tab', 'œ', '∑', '´', '®', '†', '¥', '¨', 'ˆ', 'ø', 'π', '“', '‘', '«', 'EOL',
               '{capslock}', 'å', 'ß', '∂', 'ƒ', '©', '˙', '∆', '˚', '¬', '…', 'æ', 'returnUS', 'EOL',
               '[shiftUS]', 'Ω', '≈', 'ç', '√', '∫', '˜', 'µ', '≤', '≥', '÷', '[rightshift]' ,'EOL',
               'selector', '[alt]' , 'space', '[alt]', 'EOL'],
    "all_shift":['~', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+', 'backspace', 'EOL',
                 'tab', 'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '{', '}', '|', 'EOL',
                 '{capslock}', 'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', ':', '"', 'returnUS', 'EOL',
                 '[shiftUS]', 'Z', 'X', 'C', 'V', 'B', 'N', 'M', '<', '>', '?', '[rightshift]', 'EOL',
                 'selector', '[alt]', 'space', '[alt]', 'EOL'],
    
    "all_capslock":['~', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', 'backspace', 'EOL',
                 'tab', 'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '{', '}', '|', 'EOL',
                 '{capslock}', 'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', ':', '"', 'returnUS', 'EOL',
                 '[shiftUS]', 'Z', 'X', 'C', 'V', 'B', 'N', 'M', '<', '>', '?', '[rightshift]', 'EOL',
                 'selector', '[alt]', 'space', '[alt]', 'EOL'],
    
    "all_alt_shift":['`','⁄','€','‹','›','ﬁ','ﬂ','‡','°','·','‚','—','±','backspace',
                     'tab', 'Œ','„','´','‰','ˇ','Á','¨','ˆ','Ø','∏','”','’','»','EOL',
                     '{capslock}', 'Å','Í','Î','Ï','˝','Ó','Ô','','Ò','Ú','Æ', 'returnUS', 'EOL',
                     '[shiftUS]','¸','˛','Ç','◊','ı','˜','Â','¯','˘','¿','[rightshift]', 'EOL',
                     'selector', '[alt]', 'space', '[alt]', 'EOL'],

    "all_alt_capslock":['`', '¡','™','£','¢','∞','§','¶','•','ª','º','–','≠', 'backspace', 'EOL',
                     'tab', 'Œ','„','´','‰','ˇ','Á','¨','ˆ','Ø','∏','”','’','»','EOL',
                     '{capslock}', 'Å','Í','Î','Ï','˝','Ó','Ô','','Ò','Ú','Æ', 'returnUS', 'EOL',
                     '[shiftUS]','¸','˛','Ç','◊','ı','˜','Â','¯','˘','¿','[rightshift]', 'EOL',
                     'selector', '[alt]', 'space', '[alt]', 'EOL'],
    
    "all_shift_capslock":['all_shift'],
    "all_capslock_shift":['all_shift'],
    
    "all_shift_alt":['all_alt_shift'],
    "all_capslock_alt":['all_alt_capslock'],

    "all_alt_capslock_shift":['all_alt_shift'],
    "all_alt_shift_capslock":['all_alt_shift'],
    "all_shift_alt_capslock":['all_alt_shift'],
    "all_capslock_alt_shift":['all_alt_shift'],
    "all_capslock_shift_alt":['all_alt_shift'],
    "all_shift_capslock_alt":['all_alt_shift']
};