Layout.layouts["fr"] = {"name": "Français",
    "icon" : "iVBORw0KGgoAAAANSUhEUgAAACAAAAAcCAYAAAAAwr0iAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAA2RpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDozRUYwNDlFRjVGREQxMUUyQkM2MDk5QzBCRTQyNjExQiIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDozRUYwNDlFRTVGREQxMUUyQkM2MDk5QzBCRTQyNjExQiIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ1M1IFdpbmRvd3MiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDo1OUVDNTc3RkQzNUZFMjExQjZCMkMzMkRFRjFGMDVEQSIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/PnftpCkAAAJPSURBVHjaxJfLbtNAFIZ/3+QWhSAhJbAIu26h+0jsWHfPC/St2PJCSJFYRarcBhTJrRxfMp4bM2MnxFUzNjA0Rz52FGt8Pp//zJmxJ6XEKc3HiS2cz+fBbDaLJ5NJEMcxfP//MgkhQAjBer3mSZKQMMuy8cXF53Q6HeP8PILneUcHX19/HBQk/fL16D0tuay2YNN7fFosXofL5fJVkjzg8vIdzs7sAIPT+nYCCwHEdgua3EHHDsuyjJPkHjc3KeqaQRHgMYIuU0+drq4+DALYLr7vgxnTL9X+lkLCjyOQ2zvo2GGjC0Oa5siyrROd6e0P631vPAKjtMmWGUAFqooad2FaY7tGIaTO9g6AMY48JyiK2gkAL0p7BnwPknUABDabag9gNP+XqdYDYGKQupsBrX9ZOpKgD0D1gg4ApY0EVcWeqv8/zgnPS/t49cKC1t0i1BkgZAewG4S/EkOU5dEeoKek5PSxBEzVQJMJJ+22KOwS1RFE2/L3GSiK3FydzIL0wQ4QRYDqBZ0iZEyCc0dLs5AHNfAUoa4B2pVALxJCuAGQwp5JE6uV2wBwlQEpfWcA6AEwC1JnFjBuqt3Z7kgDeMcVMACCH0ogEQRwJ4F+Eduj1FRk9KAVc84UQOQuAwOeIzj/vSfU2yQXG5HBpmKJtk7CBlgD6D/sxUPpsLWCQfbFB+8CcBN8NAqsA4ueDrczMnphB1BetzJpAK6PPE+BHvLVajUI4GeW9QIEzRrD9fmN8vfKJ8/8SbBW/k0DxMpfttfnNKJ845360+yXAAMAZl9qDcR+X2AAAAAASUVORK5CYII=",
    "sets":['all'],
    
    "all":['@', '&', 'é', '"', '\'', '(', '§', 'è', '!', 'ç', 'à', ')', '-', 'backspace', 'EOL',
           'tab', 'a', 'z', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '[^]', '$', 'return', 'EOL',
           '{capslock}', 'q', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'ù', '[`]', 'EOL',
           '[shift]', '<', 'w', 'x', 'c', 'v', 'b', 'n', ',', ';', ':', '=', '[rightshift]', 'EOL',
           'selector', '[alt]', 'space', '[alt]', 'EOL'],
    "all_alt":['•', '','ë','“','‘','{','¶','«','¡','Ç','ø','}','—', 'backspace', 'EOL',
               'tab', 'æ', 'Â', 'ê', '®', '†', 'Ú', 'º', 'î', 'œ', 'π', 'ô', '€', 'return', 'EOL',
               '{capslock}', '‡', 'Ò', '∂', 'ƒ', 'ﬁ', 'Ì', 'Ï', 'È', '¬', 'µ', 'Ù', '@', 'EOL',
               '[shift]', '≤', '‹', '≈', '©', '◊', 'ß', '~', '∞', '…', '÷', '≠', '[rightshift]' ,'EOL',
               'selector', '[alt]' , 'space', '[alt]', 'EOL'],
    "all_shift":['#', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '°', '_', 'backspace', 'EOL',
                 'tab', 'A', 'Z', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '[¨]', '*', 'return', 'EOL',
                 '{capslock}', 'Q', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'M', '%', '£', 'EOL',
                 '[shift]', '>', 'W', 'X', 'C', 'V', 'B', 'N', '?', '.', '/', '+', '[rightshift]', 'EOL',
                 'selector', '[alt]', 'space', '[alt]', 'EOL'],
    "all_capslock":['@', '&', 'é', '"', '\'', '(', '§', 'è', '!', 'ç', 'à', ')', '-', 'backspace', 'EOL',
                 'tab', 'A', 'Z', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '[¨]', '*', 'return', 'EOL',
                 '{capslock}', 'Q', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'M', '%', '£', 'EOL',
                 '[shift]', '>', 'W', 'X', 'C', 'V', 'B', 'N', '?', '.', '/', '+', '[rightshift]', 'EOL',
                 'selector', '[alt]', 'space', '[alt]', 'EOL'],    
    "all_alt_shift":['Ÿ','[´]','„','”','’','[','å','»','Û','Á','Ø',']','–','backspace','EOL',
                     'tab', 'Æ','Å','Ê','‚','™','Ÿ','ª','ï','Œ','∏','Ô','¥', 'return','EOL',
                     '{capslock}', 'Ω','∑','∆','·','·','ﬂ','Î','Í','Ë','|','Ó','‰', 'EOL',
                     '[shift]', '≥','›','⁄','¢','√','∫','ı','¿','•','\\','±','[rightshift]', 'EOL',
                     'selector', '[alt]', 'space', '[alt]', 'EOL'],
    "all_alt_capslock":['•', '','ë','“','‘','{','¶','«','¡','Ç','ø','}','—', 'backspace', 'EOL',
                     'tab', 'Æ','Å','Ê','‚','™','Ÿ','ª','ï','Œ','∏','Ô','¥', 'return','EOL',
                     '{capslock}', 'Ω','∑','∆','·','·','ﬂ','Î','Í','Ë','|','Ó','‰', 'EOL',
                     '[shift]', '≥','›','⁄','¢','√','∫','ı','¿','•','\\','±','[rightshift]', 'EOL',
                     'selector', '[alt]', 'space', '[alt]', 'EOL'],
    
    "all_^":['empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'backspace', 'EOL',
             'tab', 'â', 'empty', 'ê', 'empty', 'empty', 'empty', 'û', 'î', 'ô', 'empty', '[^]', 'empty', 'return', 'EOL',
             '{capslock}', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'EOL',
             '[shift]', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', '[rightshift]', 'EOL',
             'selector', '[alt]', 'space', '[alt]', 'EOL'],    
    "all_^_shift":['empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'backspace', 'EOL',
                   'tab', 'Â', 'empty', 'Ê', 'empty', 'empty', 'empty', 'Û', 'Î', 'Ô', 'empty', '[^]', 'empty', 'return', 'EOL',
                   '{capslock}', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'EOL',
                   '[shift]', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', '[rightshift]', 'EOL',
                   'selector', '[alt]', 'space', '[alt]', 'EOL'],    
    
    "all_`":['empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'backspace', 'EOL',
             'tab', 'à', 'empty', 'è', 'empty', 'empty', 'empty', 'ù', 'ì', 'ò', 'empty', 'empty', 'empty', 'return', 'EOL',
             '{capslock}', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', '[`]', 'EOL',
             '[shift]', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', '[rightshift]', 'EOL',
             'selector', '[alt]', 'space', '[alt]', 'EOL'],    
    "all_`_shift":['empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'backspace', 'EOL',
                   'tab', 'À', 'empty', 'È', 'empty', 'empty', 'empty', 'Ù', 'Ì', 'Ò', 'empty', 'empty', 'empty', 'return', 'EOL',
                   '{capslock}', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', '[`]', 'EOL',
                   '[shift]', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', '[rightshift]', 'EOL',
                   'selector', '[alt]', 'space', '[alt]', 'EOL'],    
    
    "all_´":['empty', '[´]', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'backspace', 'EOL',
             'tab', 'á', 'empty', 'é', 'empty', 'empty', 'empty', 'ú', 'í', 'ó', 'empty', 'empty', 'empty', 'return', 'EOL',
             '{capslock}', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'EOL',
             '[shift]', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', '[rightshift]', 'EOL',
             'selector', '[alt]', 'space', '[alt]', 'EOL'],    
    "all_´_shift":['empty', '[´]', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'backspace', 'EOL',
                   'tab', 'À', 'empty', 'È', 'empty', 'empty', 'empty', 'Ù', 'Ì', 'Ò', 'empty', 'empty', 'empty', 'return', 'EOL',
                   '{capslock}', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'EOL',
                   '[shift]', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', '[rightshift]', 'EOL',
                   'selector', '[alt]', 'space', '[alt]', 'EOL'],        
    
    "all_shift_^":['all_^_shift'],
    "all_capslock_^":['all_^_shift'],
    "all_^_capslock":['all_^_shift'],    
    
    "all_shift_capslock":['all_shift'],
    "all_capslock_shift":['all_shift'],    
    
    "all_shift_`":['all_`_shift'],
    "all_capslock_`":['all_`_shift'],
    "all_`_capslock":['all_`_shift'],    
    
    "all_shift_´":['all_´_shift'],
    "all_capslock_´":['all_´_shift'],
    "all_´_capslock":['all_´_shift'],    
    
    "all_alt_´_shift":['all_´'],
    "all_alt_shift_´":['all_´'],
    "all_shift_alt_´":['all_´'],
    "all_´_alt_shift":['all_´'],
    "all_´_shift_alt":['all_´'],
    "all_shift_´_alt":['all_´'],
    
    "all_shift_alt":['all_alt_shift'],
    "all_capslock_alt":['all_alt_capslock'],
    "all_alt_capslock_shift":['all_alt_shift'],
    "all_alt_shift_capslock":['all_alt_shift'],
    "all_shift_alt_capslock":['all_alt_shift'],
    "all_capslock_alt_shift":['all_alt_shift'],
    "all_capslock_shift_alt":['all_alt_shift'],
    "all_shift_capslock_alt":['all_alt_shift']
};