Layout.layouts["ru"] = {"name": "Русский",
    "icon":"iVBORw0KGgoAAAANSUhEUgAAACAAAAAcCAYAAAAAwr0iAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAA2RpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDozRUYwNDlGMzVGREQxMUUyQkM2MDk5QzBCRTQyNjExQiIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDozRUYwNDlGMjVGREQxMUUyQkM2MDk5QzBCRTQyNjExQiIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ1M1IFdpbmRvd3MiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDo1OUVDNTc3RkQzNUZFMjExQjZCMkMzMkRFRjFGMDVEQSIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/Pm2HIkMAAAGuSURBVHjaxFfNTgIxEJ7uAtVFTTxsTAwHPW98AXwujz6YJ30HH8ALB5O9qLhAdzutM7A/DVlQEmwnGZaWhu/r9PumIKy1EDIiCByD6XQaTyYTmaZpLKWEKPpfTsYYUEpBnuc4m80UZFl2aQMFY4skSW6KongLUf7xeHwbLRYLyWXxHYzJ2OsDR0TwSYKxGLN1QQgrNpjBbRi+D/DL/cMTXKdnsCzRC+jpKIaP+bIjUJEo5ssKVtWWEPmYhPPsmwfns33rnHmNBiptOgKaBoVDQAjRioTf94mnmefx9pp9wuO1qAWoUrsVsFQBDRX6cUMZCxKfdSpAJfkscE3ERwwjARdJ5BJA4M17wics21Z7cwSVBWsEdSg/DEgJhOmK0GiaHHqrAMNUdSteE3h5foQTErJQ5WHf5Fqxz447NmTlCFa0IGsIGCRLDIbsk8O3smts9zNHdGzY3oQeL6UGc3Md8+CPzeQoIURLoBahBfNb1Y6JX/eezobWkCiIQJJ4I1DajgAq2vv795c3CfBpx3VPYjJXlHeUqeefAjnlKxOQlOf102coyrkI/dfsR4ABAH9bW8vhkbgyAAAAAElFTkSuQmCC",
    "sets":     ['all'],
    "all":['>', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', 'backspace', 'EOL',
           'tab', 'й', 'ц', 'у', 'к', 'е', 'н', 'г', 'ш', 'щ', 'з', 'х', 'ъ', 'return', 'EOL',
           '{capslock}', 'ф', 'ы', 'в', 'а', 'п', 'р', 'о', 'л', 'д', 'ж', 'э', 'ё', 'EOL',
           '[shift]', ']', 'я', 'ч', 'с', 'м', 'и', 'т', 'ь', 'б', 'ю', '/', '[rightshift]', 'EOL',
           'selector', '[alt]', 'space', '[alt]', 'EOL'],
    "all_shift":['<', '!', '"', '№', '%', ':', ',', '.', ';', '(', ')', '_', '+', 'backspace', 'EOL',
                 'tab', 'Й', 'Ц', 'У', 'К', 'Е', 'Н', 'Г', 'Ш', 'Щ', 'З', 'Х', 'Ъ', 'return', 'EOL',
                 '{capslock}', 'Ф', 'Ы', 'В', 'А', 'П', 'Р', 'О', 'Л', 'Д', 'Ж', 'Э', 'Ё', 'EOL',
                 '[shift]', '[', 'Я', 'Ч', 'С', 'М', 'И', 'Т', 'Ь', 'Б', 'Ю', '?', '[rightshift]', 'EOL',
                 'selector', '[alt]', 'space', '[alt]', 'EOL'],
    "all_capslock":['>', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', 'backspace', 'EOL',
                 'tab', 'Й', 'Ц', 'У', 'К', 'Е', 'Н', 'Г', 'Ш', 'Щ', 'З', 'Х', 'Ъ', 'return', 'EOL',
                 '{capslock}', 'Ф', 'Ы', 'В', 'А', 'П', 'Р', 'О', 'Л', 'Д', 'Ж', 'Э', 'Ё', 'EOL',
                 '[shift]', '[', 'Я', 'Ч', 'С', 'М', 'И', 'Т', 'Ь', 'Б', 'Ю', '?', '[rightshift]', 'EOL',
                 'selector', '[alt]', 'space', '[alt]', 'EOL'],    
    "all_alt":['§', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '–', '»', 'backspace', 'EOL',
               'tab', 'ј', 'џ', 'ќ', '®', '†', 'њ', 'ѓ', 'ѕ', 'ў', '‘', '“', 'ъ', 'return', 'EOL',
               '{capslock}', 'ƒ','ы','ћ','÷','©','}','°','љ','∆','…','э','ё', 'EOL',
               '[shift]', ']','ђ','≈','≠','µ','и','™','~','≤','≥','“', '[rightshift]', 'EOL',
               'selector', '[alt]', 'space', '[alt]', 'EOL'],
    "all_alt_shift":['±','|','"','£','€','∞','¬','¶','√','\'','`','—','«', 'backspace', 'EOL',
                     'tab','Ј','Џ','Ќ','®','†','Њ','Ѓ','Ѕ','Ў','’','”','Ъ', 'return', 'EOL',
                     '{capslock}', 'ƒ','Ы','Ћ','÷','©','{','•','Љ','∆','…','Э','Ё', 'EOL',
                     '[shift]', '[','Ђ','≈','≠','µ','И','™','~','<','>','„', '[rightshift]', 'EOL',
                     'selector', '[alt]', 'space', '[alt]', 'EOL'],
    "all_alt_capslock":['§', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '–', '»', 'backspace', 'EOL',
                     'tab','Ј','Џ','Ќ','®','†','Њ','Ѓ','Ѕ','Ў','’','”','Ъ', 'return', 'EOL',
                     '{capslock}', 'ƒ','Ы','Ћ','÷','©','{','•','Љ','∆','…','Э','Ё', 'EOL',
                     '[shift]', '[','Ђ','≈','≠','µ','И','™','~','<','>','„', '[rightshift]', 'EOL',
                     'selector', '[alt]', 'space', '[alt]', 'EOL'],
    
    "all_shift_alt":['all_alt_shift'],
    "all_capslock_alt":['all_alt_capslock'],
    
    "all_shift_capslock":['all_shift'],
    "all_capslock_shift":['all_shift'],    
    
    "all_alt_capslock_shift":['all_alt_shift'],
    "all_alt_shift_capslock":['all_alt_shift'],
    "all_shift_alt_capslock":['all_alt_shift'],
    "all_capslock_alt_shift":['all_alt_shift'],
    "all_capslock_shift_alt":['all_alt_shift'],
    "all_shift_capslock_alt":['all_alt_shift']
};